version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PROJECT_NAME: STRATOS-COMMERCE V3
      ENVIRONMENT: production
      DATABASE_BASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: stratos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7
